services:
  - type: web
    name: medibuddy-api
    runtime: python
    buildCommand: |
      chmod +x scripts/setup.sh
      chmod +x scripts/build.sh
      ./scripts/build.sh
    startCommand: gunicorn wsgi:app  # Updated this line
    envVars:
      - key: HF_TOKEN
        fromGroup: hf_token
      - key: HUGGINGFACE_REPO_ID
        value: mistralai/Mixtral-8x7B-Instruct-v0.1
      - key: DB_FAISS_PATH
        value: vectorstore/db_faiss
      - key: EMBEDDING_MODEL
        value: sentence-transformers/all-MiniLM-L6-v2
      - key: CORS_ORIGINS
        value: https://your-mern-app.onrender.com,http://localhost:3000