services:
  - type: web
    name: medibuddy-api
    env: python
    buildCommand: chmod +x render_build.sh && ./render_build.sh
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_HOST
        value: 0.0.0.0
      - key: FLASK_PORT
        value: 10000
      - key: DB_FAISS_PATH
        value: vectorstore/db_faiss
      - key: HUGGINGFACE_REPO_ID
        value: mistralai/Mixtral-8x7B-Instruct-v0.1
      - key: EMBEDDING_MODEL
        value: sentence-transformers/all-MiniLM-L6-v2
      - key: HF_TOKEN
        sync: false  # You'll set this in Render dashboard