services:
  - type: web
    name: medibuddy-flask-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app --timeout 120 --workers 1 --threads 2
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
      - key: ENABLE_FALLBACK_MODE
        value: true
      - key: HUGGINGFACE_REPO_ID
        value: microsoft/DialoGPT-medium
      - key: EMBEDDING_MODEL
        value: sentence-transformers/all-MiniLM-L6-v2
      - key: MAX_SOURCES
        value: 5
      - key: MAX_CONTENT_LENGTH
        value: 500
      # Add your HuggingFace token as a secret environment variable in Render dashboard
      # - key: HF_TOKEN
      #   fromSecret: HF_TOKEN